# fly.toml app configuration file generated for my-mysqldb on 2024-03-31T15:08:24-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-mysqldb'
primary_region = 'dfw'

[build]
  image = 'mysql:8'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
