# fly.toml app configuration file generated for laragigs on 2024-03-31T16:14:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'laragigs'
primary_region = 'dfw'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_ENV = 'production'
  DB_CONNECTION = 'mysql'
  DB_HOST = 'aws.connect.psdb.cloud'
  DB_DATABASE= 'laragigs-db'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  MYSQL_ATTR_SSL_CA = '/etc/ssl/certs/ca-certificates.crt'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[mounts]
  source="storage_dir"
  destination="/var/www/html/storage"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
